### ISSUE TITLE
Cant Open (I have read that I have to modify the code but im new to this stuff so...)

### ISSUE THREAD

**Issue by crpnterr** [SkyAlumny/fortnite-launcher-for-og-servers#1]
How? If someone helps me, ill give this a star ⭐️

**Comment by SkyAlumny** [comment]
MainForm.cs you find pretty much at the Top a variable, set it to false.

**Comment by crpnterr** [comment]
> MainForm.cs you find pretty much at the Top a variable, set it to false.

ok

**Comment by crpnterr** [comment]
> MainForm.cs you find pretty much at the Top a variable, set it to false.

Cant find the variable

**Comment by SkyAlumny** [comment]
Sorry Login.cs 
Line 44

**Comment by crpnterr** [comment]
> Sorry Login.cs Line 44

ok, ty
