### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by crpnterr** [SkyAlumny/fortnite-launcher-for-og-servers#2]
Cant open the launcher for some reason, it gives errors none stop...

**Comment by SkyAlumny** [comment]
Please show me the error

**Comment by crpnterr** [comment]
> Please show me the error

I am at school currently but it says something about Win64.

**Comment by SkyAlumny** [comment]
Once you get Home you can show me the error,
and please open a issue always with full description off the issue

**Comment by crpnterr** [comment]
> Once you get Home you can show me the error, and please open a issue always with full description off the issue

![image](https://github.com/SkyAlumny/fortnite-launcher-for-og-servers/assets/129079121/07f3010b-4db5-4ef5-b489-428e5c477154)
This is the error I keep getting...

**Comment by crpnterr** [comment]
No response?

**Comment by crpnterr** [comment]
Still waiting

**Comment by NeoChairs** [comment]
send full error.

**Comment by crpnterr** [comment]
> send full error.

![271372986-07f3010b-4db5-4ef5-b489-428e5c477154](https://github.com/SkyAlumny/fortnite-launcher-for-og-servers/assets/129079121/3ca34d2c-1064-4838-becf-9e8ab0bce640)

**Comment by NeoChairs** [comment]
the full error.

**Comment by crpnterr** [comment]
> the full error.

I dont have the launcher anymore

**Comment by NeoChairs** [comment]
Then how is anyone supposed to help?

**Comment by crpnterr** [comment]
> Then how is anyone supposed to help?

i dont need help anymore

**Comment by SkyAlumny** [comment]
Change the DLL, and Emulator Links
