### ISSUE TITLE
cant launch fortnite

### ISSUE THREAD

**Issue by jarvissholee** [SkyAlumny/fortnite-launcher-for-og-servers#3]
it gives an error when i wanna launch fortnite
![image](https://github.com/SkyAlumny/fortnite-launcher-for-og-servers/assets/70055888/f77a11bc-9fd7-4248-8424-432e26e89231)

plus the error details  :

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at tetstentfrylauncher.Loader.Winform.MainForm.playButton_Click(Object sender, EventArgs e) in C:\Users\aaa\Downloads\Launcher-main\Launcher-main\TetsTentFry-Launcher\Loader\Winform\MainForm.cs:line 225
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at Guna.UI2.WinForms.Guna2Button.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
TetsTentFry-Launcher
    Assembly Version: 1.0.0.8
    Win32 Version: 1.0.0.8
    CodeBase: file:///C:/Users/aaa%aaa/Downloads/Launcher-main/Launcher-main/TetsTentFry-Launcher/bin/Release/TetsTentFry-Launcher.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9206.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Guna.UI2
    Assembly Version: 2.0.3.5
    Win32 Version: 2.0.3.5
    CodeBase: file:///C:/Users/aaa%aaa/Downloads/Launcher-main/Launcher-main/TetsTentFry-Launcher/bin/Release/Guna.UI2.DLL
----------------------------------------
Siticone.UI
    Assembly Version: 1.0.0.3
    Win32 Version: 1.0.0.3
    CodeBase: file:///C:/Users/aaa%aaa/Downloads/Launcher-main/Launcher-main/TetsTentFry-Launcher/bin/Release/Siticone.UI.DLL
----------------------------------------
Siticone.UI&
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.3
    CodeBase: file:///C:/Users/aaa%aaa/Downloads/Launcher-main/Launcher-main/TetsTentFry-Launcher/bin/Release/Siticone.UI.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by SkyAlumny** [comment]
https://github.com/SkyAlumny/fortnite-launcher-for-og-servers/blob/31d8e5847f57ab2e6c3a57b39f81aa1ed5f014d3/TetsTentFry-Launcher/Loader/Winform/MainForm.cs#L186

Change all "changingsoon" to the download links and change the dll and exe names

**Comment by jarvissholee** [comment]
i did that but this came
![image](https://github.com/SkyAlumny/fortnite-launcher-for-og-servers/assets/70055888/4fc08336-30f5-4a3f-b26d-c136cb7926c9)

**Comment by ProjectHeist-Owner** [comment]
Im facing the same issue for launching Fortnite and the install build button.

**Comment by im-silent** [comment]
> https://github.com/SkyAlumny/fortnite-launcher-for-og-servers/blob/31d8e5847f57ab2e6c3a57b39f81aa1ed5f014d3/TetsTentFry-Launcher/Loader/Winform/MainForm.cs#L186
> 
> Change all "changingsoon" to the download links and change the dll and exe names

not sure what u mean by dll and exe names?

**Comment by SkyAlumny** [comment]
Please someone show me a screenshot from line 185 to 208
MainForm.cs

**Comment by im-silent** [comment]
![image](https://github.com/SkyAlumny/fortnite-launcher-for-og-servers/assets/107319949/9e2c754a-4f8f-48c9-bf3a-06cfb1c3e169)

**Comment by im-silent** [comment]
> Please someone show me a screenshot from line 185 to 208 MainForm.cs

whats ur discord?

**Comment by SkyAlumny** [comment]
https://discord.gg/KK6Tw95k5Z

And just as i said the repo includes files that you need to upload somewhere so you can change the links at the download and enter the right filename, you need to have a dll too that injects to get the to right server ip.

**Comment by im-silent** [comment]
> https://discord.gg/KK6Tw95k5Z
> 
> And just as i said the repo includes files that you need to upload somewhere so you can change the links at the download and enter the right filename, you need to have a dll too that injects to get the to right server ip.

do you have a dll or do i have to make one?

**Comment by SkyAlumny** [comment]
> > https://discord.gg/KK6Tw95k5Z
> > And just as i said the repo includes files that you need to upload somewhere so you can change the links at the download and enter the right filename, you need to have a dll too that injects to get the to right server ip.
> 
> do you have a dll or do i have to make one?

https://github.com/Milxnor/Cobalt

**Comment by im-silent** [comment]
> > > https://discord.gg/KK6Tw95k5Z
> > > And just as i said the repo includes files that you need to upload somewhere so you can change the links at the download and enter the right filename, you need to have a dll too that injects to get the to right server ip.
> > 
> > 
> > do you have a dll or do i have to make one?
> 
> https://github.com/Milxnor/Cobalt

what if i want it not to be multiplayer?

**Comment by SkyAlumny** [comment]
Then Play alone

**Comment by im-silent** [comment]
> Then Play alone

this is confusing what payment methods do you take maybe i can pay you to set it up

**Comment by SkyAlumny** [comment]
DM me on Discord

**Comment by im-silent** [comment]
> DM me on Discord

i did

**Comment by SkyAlumny** [comment]
So, you all have the same issue.
You just need to change the links...
