### ISSUE TITLE
Excpetion

### ISSUE THREAD

**Issue by paratafine** [SkyAlumny/fortnite-launcher-for-og-servers#7]
![Cattura](https://github.com/SkyAlumny/fortnite-launcher-for-og-servers/assets/85792462/52ad8140-f893-48aa-9897-bbe8d19ea3c0)
I get this exception when clicking Play

**Comment by Thundergoltn** [comment]
You can actually run it 😥I cant even figure out how to launch the launcher. Please let me know how

**Comment by SkyAlumny** [comment]
This issue is old but it pretty sure you dont have fortnite installed at the path it should be
